### ISSUE TITLE
Can you please provide a sample command to run the java agent recipe

### ISSUE THREAD

**Issue by robertcurcio** [Tripwire/chef-tripwire_agent#24]
I'm not that great at Chef, and I'd like to run this cookbook locally, to install the Tripwire agent on 2 machines. Can you please provide a sample command to get us going? Thank You.

**Comment by pfaffle** [comment]
If you only need to run it on two systems, it might be more straightforward to use the command-line installation options, which you can see by running the agent installer with the `--help` flag. Usually, installing software via Chef assumes you have some infrastructure in place to support it.

But, if you want to use Chef, here are some basic instructions for running it in local mode on a system, assuming you don't have a Chef server.

1. **Get cookbooks**
First, you have to fetch the necessary cookbooks. It's easiest to do this using a tool like [Berkshelf](https://github.com/berkshelf/berkshelf), which comes with the [ChefDK](https://downloads.chef.io/chefdk). I'd recommend installing the ChefDK on your own workstation as the easiest way to get it. After that, you can create a basic Berksfile to specify the cookbooks to download:
```ruby
source 'https://supermarket.chef.io'
cookbook 'tripwire_agent'
```
Then run `berks vendor cookbooks` and it will automatically fetch the cookbook and its dependencies and save them to a 'cookbooks' directory.

2. **Copy cookbooks and agent installer to target system**
The chef-client would normally fetch the cookbooks from its Chef server, but we're running in local mode. So, copy the cookbooks directory created by Berkshelf to the target node.

The agent installer will also need to be accessible by Chef. If you have an HTTP server available you can put it on that. Otherwise it'll need to be mounted on or copied to the target system.

3. **Create attributes file to configure Chef**
This will tell Chef how to configure the agent as it runs the installer. See the [Readme](https://github.com/Tripwire/chef-tripwire_agent#java-parameters) for all the configurable options. A minimal example would be:
```json
{
  "tripwire_agent": {
    "installer": "[path to installer]",
    "java": {
      "console": "[your TE console host]",
      "services_password": "[services passphrase]"
    }
  }
}
```
Replace the above sections in square brackets with the proper configuration for your environment. The installer path can either be a local filesystem path or a HTTP URI.

4. **Run Chef**
Finally you can run Chef to configure your system and install the agent. You'll want to run Chef in the parent directory of where your cookbooks directory is. Here's an example command-line:
```bash
$ chef-client -z -j ./attributes.json -o recipe[tripwire_agent::java_agent]
```

Hope that helps.

**Comment by bespokebob** [comment]
Closing because it looks like this was answered (in great detail).
